version: '3.8'
services:
  gateway:
    build: ./docker/gateway
    container_name: gateway
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE   # se necessário para carregar módulos, mas geralmente nftables já está no kernel
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "8080:8080"
    networks:
      wan:
      lan:
        ipv4_address: 192.168.100.1

  cliente1:
    build: ./docker/client
    container_name: cliente1
    networks:
      lan:
    depends_on:
      - gateway

  # cliente2, etc.

networks:
  wan:
    driver: bridge
  lan:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.100.0/24